[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build]
  publish = "src"
  command = "npm run build:noop"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

